// view/vue/0.0.2/pro/src/view/com/pro/code/plugin/dt/dt-list/dt-list.vue
<style lang="less">
  @import './dt-list.less';
</style>

<template>
  <div>
    <Card>
      <Button class="button-spacing" type="primary" @click="addDt()">新建</Button>
      <Button class="button-spacing" type="dashed" @click="upDt()" v-if="selectDataRowLength === 1">编辑</Button>
      <Button class="button-spacing" type="error" @click="delDt()" v-if="selectDataRowLength > 0">删除</Button>
      <Button class="button-spacing" @click="detailDt()" v-if="selectDataRowLength === 1">详情</Button>
      <Table :columns="columns" :data="dataSet" @on-selection-change="selectRow($event)"></Table>
      <Spin size="large" fix v-if="spinShow"></Spin>
    </Card>
  </div>
</template>

<script>
import { mapState, mapMutations, mapActions, mapGetters } from 'vuex'

export default {
  data () {
    return {
      columns: [
        { type: 'selection', width: 50, align: 'center', fixed: 'left' },
        { title: '表名', key: 'dtName', width: 200 },
        { title: '表名注释', key: 'dtNameAnnotation', width: 150 },
        { title: '首字母大写实体类名', key: 'initialCaseEntityName', width: 180 },
        { title: '首字母小写实体类名', key: 'initialLowercaseEntityName', width: 180 },
        { title: '项目路径', key: 'proPath', width: 500 },
        { title: '项目全称', key: 'proAllName', width: 400 },
        { title: '项目名称', key: 'proName', width: 300 }
      ]
    }
  },
  computed: {
    ...mapState('dtStore', [
      'dataSet',
      'spinShow',
      'selectDataRow',
      'selectDataRowLength'
    ]),
    ...mapGetters('dtStore', [
    ])
  },
  methods: {
    ...mapMutations([
      'addTag'
    ]),
    ...mapMutations('dtStore', [
      'setDataSet',
      'changeSpinShow',
      'setSelectDataRow'
    ]),
    ...mapActions('dtStore', [
      'getAllDt',
      'batchRemoveDt'
    ]),
    addDt () {
      const route = {
        name: 'dt-edit',
        params: {
          dtId: 'add'
        },
        meta: {
          title: '编辑数据库表'
        }
      }
      this.addTag({
        route: route,
        type: 'push'
      })
      this.$router.push(route)
      // this.$router.push({ name: 'dt-edit' })
    },
    getDataSet () {
      this.changeSpinShow(true)
      this.getAllDt().then(res => {
        if (res.data.isSuccess && res.data.statusCode === 200) {
          this.setDataSet(res.data.data)
          this.selectRow([])
          this.changeSpinShow(false)
        } else {
          this.$Message.error({ content: res.data.msg, duration: 6 })
          this.changeSpinShow(false)
        }
      }).catch(result => {
        this.$Message.error({ content: '请求失败！状态码 ' + result.response.status + ' ' + result.response.statusText, duration: 6 })
        this.changeSpinShow(false)
      })
    },
    selectRow (selection) {
      this.setSelectDataRow(selection)
    },
    delDt () {
      this.changeSpinShow(true)
      this.batchRemoveDt(this.selectDataRow).then(res => {
        if (res.data.isSuccess && res.data.statusCode === 200) {
          this.$Message.success({ content: '数据库表信息删除成功.', duration: 3 })
          this.selectRow([])
          this.getDataSet()
          this.changeSpinShow(false)
        } else {
          this.$Message.error({ content: res.data.msg, duration: 6 })
          this.changeSpinShow(false)
        }
      }).catch(result => {
        this.$Message.error({ content: '请求失败！状态码 ' + result.response.status + ' ' + result.response.statusText, duration: 6 })
        this.changeSpinShow(false)
      })
    },
    upDt () {
      const route = {
        name: 'dt-edit',
        params: {
          dtId: this.selectDataRow[0].dtId
        },
        meta: {
          title: '编辑数据库表'
        }
      }
      this.addTag({
        route: route,
        type: 'push'
      })
      this.$router.push(route)
    },
    detailDt () {
      const route = {
        name: 'dt-detail',
        params: {
          dtId: this.selectDataRow[0].dtId
        },
        meta: {
          title: '数据库表详情'
        }
      }
      this.addTag({
        route: route,
        type: 'push'
      })
      this.$router.push(route)
    }
  },
  mounted () {
    this.getDataSet()
  }
}
</script>

// view/angular/0.0.2/pro/src/app/routes/com/pro/common/module/autocode/dt/dt-list/dt-list.component.ts
import { Component, OnInit } from '@angular/core';
import { NzMessageService } from 'ng-zorro-antd';
import { Router } from '@angular/router';
import { SimpleTableColumn, SimpleTableChange, SimpleTableFilter, SimpleTableButton } from '@delon/abc';

import { DtService } from '@com/pro/common/module/autocode/dt/dt.service';
import { CodingService } from '@com/pro/common/module/autocode/coding/coding.service';

@Component({
  selector: 'dt-list',
  templateUrl: './dt-list.component.html',
  styleUrls: ['./dt-list.component.css']
})
export class DtListComponent implements OnInit {
  dataSet: any[];
  list: any[];
  listLength: number;
  count: number;
  rows: number;
  page: number;
  isSpinning: boolean;
  columns: SimpleTableColumn[] = [
    { title: '数据库表编号', index: 'dtId', type: 'checkbox', fixed: 'left', width: '1px' },
    // { title: '数据库表sql', index: 'dtSql', width: '100px' },
    { title: '表名', index: 'dtName', width: '200px' },
    { title: '表名注释', index: 'dtNameAnnotation', width: '200px' },
    { title: '数据库表前缀', index: 'dtPrefix', width: '200px' },
    { title: '首字母大写实体类名', index: 'initialCaseEntityName', width: '200px' },
    { title: '首字母小写实体类名', index: 'initialLowercaseEntityName', width: '200px' },
    { title: '项目路径', index: 'proPath', width: '800px' },
    { title: '项目全称', index: 'proAllName', width: '500px' },
    { title: '项目名称', index: 'proName', width: '200px' },
    {
      title: '操作',
      fixed: 'right',
      width: '250px',
      buttons: [
        {
          text: '编辑',
          click: (record: any, modal: any) => this.router.navigate([ '/pro/common/module/autocode/dt/edit/' + record['dtId'] ])
        },
        {
          text: '删除',
          type: 'del',
          click: (record: any) => this.remove(record)
        },
        {
          text: '详情',
          click: (record: any, modal: any) => this.router.navigate([ '/pro/common/module/autocode/dt/detail/' + record['dtId'] ])
        },
        {
          text: '更多',
          children: [
            {
              text: `提取`,
              click: (record: any) => this.extract(record),
              format: (record: any) => `<i class="anticon anticon-tool"></i> 提取`
            }
          ]
        }
      ]
    }
  ];

  constructor(
    private msg: NzMessageService,
    private router: Router,
    private dtService: DtService,
    private codingService: CodingService
  ) { }

  ngOnInit() {
    this.getDataSet();
  }

  addDt() {
    this.router.navigate([ '/pro/common/module/autocode/dt/edit' ]);
  }

  upDt() {
    this.router.navigate([ '/pro/common/module/autocode/dt/edit/' + this.list[0]['dtId'] ]);
  }

  delDt() {
    this.batchRemove();
  }

  detailDt() {
    this.router.navigate([ '/pro/common/module/autocode/dt/detail/' + this.list[0]['dtId'] ]);
  }

  checkboxChange(list: any[]) {
    this.listLength = list.length;
    this.list = list;
  }

  pageIndexChange(nzPageIndex) {
    this.page = nzPageIndex;
    this.getDataSet();
  }

  pageSizeChange(nzPageSize) {
    this.rows = nzPageSize;
    this.page = 1;
    this.getDataSet();
  }

  getDataSet() {
    this.isSpinning = true;
    this.dtService.paging(this.rows, this.page)
      .subscribe(
        data => {
          if (data['isSuccess'] && data['statusCode'] === 200) {
            this.dataSet = data['data'];
            this.count = data['count'];
            this.rows = data['rows'];
            this.page = data['page'];
            this.isSpinning = false;
          } else {
            this.msg.error(data['msg'], { nzDuration: 6000 });
            this.isSpinning = false;
          }
        },
        error => {
          this.msg.error('请求失败！状态码 ' + error['status'] + ' ' + error['statusText']);
          this.isSpinning = false;
        }
      );
  }

  remove(record) {
    this.isSpinning = true;
    this.dtService.remove(record)
      .subscribe(
        data => {
          if (data['isSuccess'] && data['statusCode'] === 200) {
            this.msg.success(`数据库表信息删除成功.`);
            this.getDataSet();
          } else {
            this.msg.error(data['msg'], { nzDuration: 6000 });
            this.isSpinning = false;
          }
        },
        error => {
          this.msg.error('请求失败！状态码 ' + error['status'] + ' ' + error['statusText']);
          this.isSpinning = false;
        }
      );
  }

  batchRemove() {
    this.isSpinning = true;
    this.dtService.batchRemove(this.list)
      .subscribe(
        data => {
          if (data['isSuccess'] && data['statusCode'] === 200) {
            this.msg.success(`数据库表信息删除成功.`);
            this.getDataSet();
            this.list = Array.of();
            this.listLength = this.list.length;
          } else {
            this.msg.error(data['msg'], { nzDuration: 6000 });
            this.isSpinning = false;
          }
        },
        error => {
          this.msg.error('请求失败！状态码 ' + error['status'] + ' ' + error['statusText']);
          this.isSpinning = false;
        }
      );
  }

  extract(record) {
    this.isSpinning = true;
    this.codingService.extract(record['dtId'])
      .subscribe(
        data => {
          if (data['isSuccess'] && data['statusCode'] === 200) {
            this.msg.success(`数据库表信息提取成功.`);
            this.getDataSet();
          } else {
            this.msg.error(data['msg'], { nzDuration: 6000 });
            this.isSpinning = false;
          }
        },
        error => {
          this.msg.error('请求失败！状态码 ' + error['status'] + ' ' + error['statusText']);
          this.isSpinning = false;
        }
      );
  }
}
