// view/angular/0.0.2/pro/src/app/routes/com/pro/code/plugin/dt/dt-edit/dt-edit.component.ts
import { Component, OnInit } from '@angular/core';
import { NzMessageService } from 'ng-zorro-antd';
import { Location } from '@angular/common';
import { Router, ActivatedRoute } from '@angular/router';
import { AbstractControl, FormBuilder, FormGroup, Validators } from '@angular/forms';

import { Dt } from '@com/pro/code/plugin/dt/dt';
import { DtService } from '@com/pro/code/plugin/dt/dt.service';

@Component({
  selector: 'dt-edit',
  templateUrl: './dt-edit.component.html',
  styleUrls: ['./dt-edit.component.css']
})
export class DtEditComponent implements OnInit {
  dtForm: FormGroup;
  dt: Dt = new Dt();
  submitting = false;
  continue: boolean;
  isSpinning: boolean = true;

  constructor(
    private msg: NzMessageService,
    private location: Location,
    private router: Router,
    private route: ActivatedRoute,
    private fb: FormBuilder,
    private dtService: DtService
  ) { }

  ngOnInit(): void {
    this.dtForm = this.fb.group({
      dtId: [null, Validators.compose([])],
      dtSql: [null, Validators.compose([Validators.required])],
      dtName: [null, Validators.compose([])],
      dtNameAnnotation: [null, Validators.compose([])],
      dtPrefix: [null, Validators.compose([])],
      initialCaseEntityName: [null, Validators.compose([])],
      initialLowercaseEntityName: [null, Validators.compose([])],
      proPath: [null, Validators.compose([])],
      proAllName: [null, Validators.compose([])],
      proName: [null, Validators.compose([])]
    });
    this.dt.dtId = this.route.snapshot.paramMap.get('dtId');
    if (this.dt.dtId) {
      this.dtService.getByPk(this.dt.dtId)
        .subscribe(
          data => {
            if (data['isSuccess'] && data['statusCode'] === 200) {
              this.dt = data['data'][0];
              this.dtForm.patchValue(this.dt);
              this.isSpinning = false;
            } else {
              this.msg.error(data['msg'], { nzDuration: 6000 });
              this.isSpinning = false;
            }
          },
          error => {
            this.msg.error('请求失败！状态码 ' + error['status'] + ' ' + error['statusText']);
            this.isSpinning = false;
          }
        );
    } else {
      this.isSpinning = false;
    }
  }

  get dtId() {
    return this.dtForm.controls['dtId'];
  }

  get dtSql() {
    return this.dtForm.controls['dtSql'];
  }

  get dtName() {
    return this.dtForm.controls['dtName'];
  }

  get dtNameAnnotation() {
    return this.dtForm.controls['dtNameAnnotation'];
  }

  get dtPrefix() {
    return this.dtForm.controls['dtPrefix'];
  }

  get initialCaseEntityName() {
    return this.dtForm.controls['initialCaseEntityName'];
  }

  get initialLowercaseEntityName() {
    return this.dtForm.controls['initialLowercaseEntityName'];
  }

  get proPath() {
    return this.dtForm.controls['proPath'];
  }

  get proAllName() {
    return this.dtForm.controls['proAllName'];
  }

  get proName() {
    return this.dtForm.controls['proName'];
  }

  submit() {
    for (const i in this.dtForm.controls) {
      this.dtForm.controls[i].markAsDirty();
      this.dtForm.controls[i].updateValueAndValidity();
    }
    if (this.dtForm.invalid) return;
    this.submitting = true;
    let dtId = this.dt.dtId;
    if (dtId && dtId !== '') {
      this.dt = Object.assign(this.dt, this.dtForm.value);
      this.dt.dtId = dtId;
      this.dtService.update(this.dt)
        .subscribe(
          data => {
            if (data['isSuccess'] && data['statusCode'] === 200) {
              this.submitting = false;
              this.msg.success(`数据库表信息修改成功.`);
              this.resetForm();
              this.dt = new Dt();
              if (!this.continue)
                this.router.navigate([ '/pro/code/plugin/dt/list' ]);
            } else {
              setTimeout(() => this.submitting = false, 3000);
              this.msg.error(data['msg'], { nzDuration: 10000 });
            }
          },
          error => {
            this.submitting = false;
            this.msg.error('请求失败！状态码 ' + error['status'] + ' ' + error['statusText']);
          }
        );
    } else {
      this.dtService.save(Object.assign(this.dt, this.dtForm.value))
        .subscribe(
          data => {
            if (data['isSuccess'] && data['statusCode'] === 200) {
              this.submitting = false;
              this.msg.success(`数据库表信息保存成功.`);
              this.resetForm();
              this.dt = new Dt();
              if (!this.continue)
                this.router.navigate([ '/pro/code/plugin/dt/list' ]);
            } else {
              setTimeout(() => this.submitting = false, 3000);
              this.msg.error(data['msg'], { nzDuration: 10000 });
            }
          },
          error => {
            this.submitting = false;
            this.msg.error('请求失败！状态码 ' + error['status'] + ' ' + error['statusText']);
          }
        );
    }
  }

  goBack(): void {
    this.location.back();
  }

  resetForm(): void {
    this.dtForm.reset();
  }

  isContinue(): void {
    this.continue = true;
  }

  isNotContinue(): void {
    this.continue = false;
  }
}

<page-header [title]="'编辑数据库表信息'">
  请填写数据库表信息。
</page-header>
<nz-card [nzBordered]="false">
  <nz-spin [nzSize]="'large'" nzTip="Loading..." [nzSpinning]="isSpinning">
    <form nz-form [formGroup]="dtForm" (ngSubmit)="submit()">
      <nz-form-item>
        <nz-form-label nzXs="24" nzSm="7" nzRequired nzFor="dtSql">数据库表sql</nz-form-label>
        <nz-form-control nzXs="24" nzSm="12" nzMd="10">
          <textarea nz-input [nzAutosize]="{ minRows: 5 }" formControlName="dtSql" id="dtSql" placeholder="输入数据库表sql"></textarea>
          <ng-container *ngIf="dtSql.dirty || dtSql.touched">
            <nz-form-explain *ngIf="dtSql.errors?.required">请输入数据库表sql</nz-form-explain>
          </ng-container>
        </nz-form-control>
      </nz-form-item>
      <nz-form-item>
        <nz-form-label nzXs="24" nzSm="7" nzFor="dtPrefix">数据库表前缀</nz-form-label>
        <nz-form-control nzXs="24" nzSm="12" nzMd="10">
          <input nz-input formControlName="dtPrefix" id="dtPrefix" placeholder="输入数据库表前缀">
        </nz-form-control>
      </nz-form-item>
      <nz-form-item>
        <nz-form-label nzXs="24" nzSm="7" nzFor="proPath">项目路径</nz-form-label>
        <nz-form-control nzXs="24" nzSm="12" nzMd="10">
          <input nz-input formControlName="proPath" id="proPath" placeholder="输入项目路径">
        </nz-form-control>
      </nz-form-item>
      <nz-form-item>
        <nz-form-label nzXs="24" nzSm="7" nzFor="proAllName">项目全称</nz-form-label>
        <nz-form-control nzXs="24" nzSm="12" nzMd="10">
          <input nz-input formControlName="proAllName" id="proAllName" placeholder="输入项目全称">
        </nz-form-control>
      </nz-form-item>
      <nz-form-item>
        <nz-form-label nzXs="24" nzSm="7" nzFor="proName">项目名称</nz-form-label>
        <nz-form-control nzXs="24" nzSm="12" nzMd="10">
          <input nz-input formControlName="proName" id="proName" placeholder="输入项目名称">
        </nz-form-control>
      </nz-form-item>
      <nz-form-item>
        <nz-form-control [nzXs]="{ span: 24, offset: 0 }" [nzSm]="{ span: 10, offset: 7 }">
          <a nz-button class="ml-sm" (click)="goBack()">取消</a>
          <a nz-button nzType="dashed" (click)="resetForm()">重置</a>
          <button nz-button nzType="primary" type="submit" [nzLoading]="submitting" (click)="isContinue()">保存并继续录入</button>
          <button nz-button nzType="primary" type="submit" [nzLoading]="submitting" (click)="isNotContinue()">保存</button>
        </nz-form-control>
      </nz-form-item>
    </form>
  </nz-spin>
</nz-card>

// view/vue/0.0.2/pro/src/view/com/pro/code/plugin/dt/dt-edit/dt-edit.vue
<style lang="less">
  @import './dt-edit.less';
</style>

<template>
  <div>
    <Card>
      <Form ref="dtForm" :model="dt" :rules="dtFormValidate" :label-width="120">
        <Row type="flex" justify="center">
          <Col :xs="24" :sm="20" :md="18" :lg="14">
            <FormItem label="数据库表sql：" prop="dtSql">
              <Input v-model="dt.dtSql" type="textarea" :rows="6" placeholder="输入数据库表sql"></Input>
            </FormItem>
          </Col>
          <Col :xs="24" :sm="20" :md="18" :lg="14">
            <FormItem label="数据库表前缀：" prop="dtPrefix">
              <Input v-model="dt.dtPrefix" placeholder="输入数据库表前缀"></Input>
            </FormItem>
          </Col>
          <Col :xs="24" :sm="20" :md="18" :lg="14">
            <FormItem label="项目路径：" prop="proPath">
              <Input v-model="dt.proPath" placeholder="输入项目路径"></Input>
            </FormItem>
          </Col>
          <Col :xs="24" :sm="20" :md="18" :lg="14">
            <FormItem label="项目全称：" prop="proAllName">
              <Input v-model="dt.proAllName" placeholder="输入项目全称"></Input>
            </FormItem>
          </Col>
          <Col :xs="24" :sm="20" :md="18" :lg="14">
            <FormItem label="项目名称：" prop="proName">
              <Input v-model="dt.proName" placeholder="输入项目名称"></Input>
            </FormItem>
          </Col>
          <Col :xs="24" :sm="20" :md="18" :lg="14">
            <FormItem>
              <Button class="button-spacing" @click="gotoList()">取消</Button>
              <Button class="button-spacing" @click="reset()">重置</Button>
              <Button class="button-spacing" type="primary" @click="saveAdd()" :loading="submitting">保存并继续录入</Button>
              <Button class="button-spacing" type="primary" @click="save()" :loading="submitting">保存</Button>
            </FormItem>
          </Col>
        </Row>
      </Form>
    </Card>
  </div>
</template>

<script>
import { mapState, mapMutations, mapActions, mapGetters } from 'vuex'
import { getDt } from '@/view/com/pro/code/plugin/dt/dt'

export default {
  data () {
    return {
      dt: getDt(),
      dtFormValidate: {
        dtSql: [
          { required: true, message: '数据库表sql不能为空', trigger: 'blur' }
        ]
      }
    }
  },
  computed: {
    ...mapState('dtStore', [
      'submitting',
      'continue'
    ]),
    ...mapGetters('dtStore', [
    ])
  },
  methods: {
    ...mapMutations('dtStore', [
      'changeSubmitting',
      'changeContinue'
    ]),
    ...mapActions('dtStore', [
      'saveDt',
      'getDtByPk',
      'updateDt'
    ]),
    gotoList () {
      this.$router.push({ name: 'dt-list' })
    },
    save () {
      this.changeContinue(false)
      this.submit()
    },
    saveAdd () {
      this.changeContinue(true)
      this.submit()
    },
    reset () {
      this.$refs.dtForm.resetFields()
    },
    submit () {
      this.changeSubmitting(true)
      this.$refs.dtForm.validate((valid) => {
        if (valid) {
          if (this.dt.dtId !== 'add') {
            this.updateDt(this.dt).then(res => {
              if (res.data.isSuccess && res.data.statusCode === 200) {
                this.$Message.success({ content: '数据库表信息修改成功.', duration: 3 })
                this.reset()
                this.dt = getDt()
                this.dt.dtId = 'add'
                this.changeSubmitting(false)
                if (!this.continue) {
                  this.gotoList()
                }
              } else {
                this.$Message.error({ content: res.data.msg, duration: 6 })
                this.changeSubmitting(false)
              }
            }).catch(result => {
              this.$Message.error({ content: '请求失败！状态码 ' + result.response.status + ' ' + result.response.statusText, duration: 6 })
              this.changeSubmitting(false)
            })
          } else {
            this.saveDt(this.dt).then(res => {
              if (res.data.isSuccess && res.data.statusCode === 200) {
                this.$Message.success({ content: '数据库表信息保存成功.', duration: 3 })
                this.reset()
                this.dt = getDt()
                this.dt.dtId = 'add'
                this.changeSubmitting(false)
                if (!this.continue) {
                  this.gotoList()
                }
              } else {
                this.$Message.error({ content: res.data.msg, duration: 6 })
                this.changeSubmitting(false)
              }
            }).catch(result => {
              this.$Message.error({ content: '请求失败！状态码 ' + result.response.status + ' ' + result.response.statusText, duration: 6 })
              this.changeSubmitting(false)
            })
          }
        } else {
          setTimeout(() => this.changeSubmitting(false), 3000)
        }
      })
    }
  },
  created () {
    this.dt.dtId = this.$route.params.dtId
    if (this.dt.dtId !== 'add') {
      this.getDtByPk(this.dt.dtId).then(res => {
        if (res.data.isSuccess && res.data.statusCode === 200) {
          Object.assign(this.dt, res.data.data[0])
        } else {
          this.$Message.error({ content: res.data.msg, duration: 6 })
        }
      }).catch(result => {
        this.$Message.error({ content: '请求失败！状态码 ' + result.response.status + ' ' + result.response.statusText, duration: 6 })
      })
    }
  }
}
</script>
